import type { Agent, AgentId, JarvisData } from "./types";

const AGENT_DEFS: { id: AgentId; department: string; color: string }[] = [
  { id: "ARES", department: "Marketing", color: "#EF4444" },
  { id: "HERMES", department: "Ventas", color: "#F59E0B" },
  { id: "ATLAS", department: "Operaciones", color: "#10B981" },
  { id: "NEXUS", department: "IA & Auto", color: "#8B5CF6" },
  { id: "APOLLO", department: "Diseño", color: "#EC4899" },
  { id: "MUSE", department: "Contenido", color: "#06B6D4" },
  { id: "FORGE", department: "Dev & Infra", color: "#6366F1" },
  { id: "ORACLE", department: "Finanzas", color: "#14B8A6" },
  { id: "HIVE", department: "RRHH", color: "#A855F7" },
  { id: "ECHO", department: "Atención", color: "#3B82F6" },
  { id: "LEX", department: "Legal", color: "#64748B" },
  { id: "ZEUS", department: "Estrategia", color: "#1E6FFF" },
];

export const AGENTS: Agent[] = AGENT_DEFS.map((a) => ({ ...a, name: a.id }));

export const MOCK_JARVIS_DATA: JarvisData = {
  agencySemaphore: "yellow",
  greeting: "Buenos días, Jordy",
  dateLabel: "Sábado 20 de junio 2026 · Semana 25",

  kpis: [
    {
      id: "revenue-ytd",
      label: "Revenue YTD",
      value: "$14,200",
      caption: "USD acumulado 2026",
      delta: { value: 12, label: "vs mes ant.", direction: "up" },
      sparkline: [0, 8000, 14200],
    },
    {
      id: "pipeline",
      label: "Pipeline ponderado",
      value: "$45,000",
      caption: "3 propuestas activas",
      delta: { value: 8, label: "vs semana ant.", direction: "up" },
      sparkline: [32000, 38000, 42000, 45000],
    },
    {
      id: "leads-week",
      label: "Leads esta semana",
      value: "8",
      caption: "2 cualificados ≥6",
      delta: { value: 2, label: "vs semana ant.", direction: "up" },
      sparkline: [4, 6, 5, 8],
    },
    {
      id: "clients",
      label: "Clientes activos",
      value: "2",
      caption: "Grupo Juana Sánchez + 1",
      sparkline: [1, 1, 2, 2],
    },
    {
      id: "roas",
      label: "ROAS promedio",
      value: "3.2x",
      caption: "Meta Ads · 30 días",
      delta: { value: 0.4, label: "vs mes ant.", direction: "up" },
      sparkline: [2.1, 2.6, 2.9, 3.2],
    },
    {
      id: "engagement-ig",
      label: "Engagement IG",
      value: "4.8%",
      caption: "últimos 7 días",
      delta: { value: 0.3, label: "pp", direction: "up" },
      sparkline: [3.9, 4.1, 4.5, 4.8],
    },
    {
      id: "tasks-pending",
      label: "Tareas pendientes",
      value: "12",
      caption: "4 en working",
      sparkline: [15, 14, 13, 12],
    },
    {
      id: "capacity",
      label: "Capacidad (2 sem)",
      value: "78%",
      caption: "semáforo 🟡",
      delta: { value: 5, label: "vs plan", direction: "up" },
      sparkline: [62, 68, 74, 78],
    },
  ],

  tasks: [
    {
      id: "t1",
      title: "Automatización WhatsApp HERMES-CLOSE",
      agent: "NEXUS",
      client: "Grupo Juana Sánchez",
      priority: "high",
      status: "working",
      progress: 65,
      deadline: "2026-06-22",
      tags: ["automation", "crm"],
    },
    {
      id: "t2",
      title: "Reporte semanal cliente GJS",
      agent: "ORACLE",
      client: "Grupo Juana Sánchez",
      priority: "high",
      status: "pending",
      deadline: "2026-06-23",
      tags: ["reporting"],
    },
    {
      id: "t3",
      title: "Creativos Meta Ads Q3",
      agent: "ARES",
      priority: "medium",
      status: "working",
      progress: 40,
      deadline: "2026-06-25",
      tags: ["ads", "creative"],
    },
    {
      id: "t4",
      title: "Landing sector salud v2",
      agent: "APOLLO",
      priority: "medium",
      status: "pending",
      deadline: "2026-06-28",
      tags: ["landing", "salud"],
    },
    {
      id: "t5",
      title: "Calendario contenido LinkedIn",
      agent: "MUSE",
      priority: "low",
      status: "working",
      progress: 80,
      deadline: "2026-06-21",
      tags: ["content", "linkedin"],
    },
    {
      id: "t6",
      title: "Propuesta Eco · Clínica dental Medellín",
      agent: "HERMES",
      client: "Prospecto",
      priority: "high",
      status: "review",
      progress: 95,
      deadline: "2026-06-20",
      tags: ["proposal", "salud"],
    },
    {
      id: "t7",
      title: "Conectar base FINANZAS Airtable",
      agent: "FORGE",
      priority: "medium",
      status: "pending",
      deadline: "2026-06-30",
      tags: ["infra", "airtable"],
    },
    {
      id: "t8",
      title: "Revisión contrato retainer Pro",
      agent: "LEX",
      client: "E-commerce Cali",
      priority: "medium",
      status: "backlog",
      deadline: "2026-07-02",
      tags: ["legal"],
    },
    {
      id: "t9",
      title: "OKR Q2 review con ZEUS",
      agent: "ZEUS",
      priority: "high",
      status: "pending",
      deadline: "2026-06-24",
      tags: ["strategy"],
    },
    {
      id: "t10",
      title: "Bot FAQ WhatsApp · fase 1",
      agent: "ECHO",
      client: "Grupo Juana Sánchez",
      priority: "medium",
      status: "working",
      progress: 30,
      deadline: "2026-07-05",
      tags: ["whatsapp", "support"],
    },
    {
      id: "t11",
      title: "Dashboard JARVIS v1 deploy",
      agent: "FORGE",
      priority: "high",
      status: "working",
      progress: 85,
      deadline: "2026-06-20",
      tags: ["panel", "jarvis"],
    },
    {
      id: "t12",
      title: "Onboarding freelancer comercial",
      agent: "HIVE",
      priority: "low",
      status: "backlog",
      deadline: "2026-07-15",
      tags: ["hiring"],
    },
    {
      id: "t13",
      title: "Optimizar flujo Make · leads web",
      agent: "NEXUS",
      priority: "medium",
      status: "done",
      deadline: "2026-06-18",
      tags: ["make", "leads"],
    },
    {
      id: "t14",
      title: "Post LinkedIn caso éxito e-commerce",
      agent: "MUSE",
      priority: "low",
      status: "done",
      deadline: "2026-06-17",
      tags: ["content"],
    },
    {
      id: "t15",
      title: "Seguimiento propuesta restaurante Madrid",
      agent: "HERMES",
      client: "Prospecto",
      priority: "medium",
      status: "done",
      deadline: "2026-06-16",
      tags: ["follow-up"],
    },
  ],

  projects: [
    {
      id: "p1",
      client: "Grupo Juana Sánchez",
      status: "Delivery activo",
      progress: 72,
      risk: "green",
      tier: "Pro",
    },
    {
      id: "p2",
      client: "E-commerce Cali",
      status: "Onboarding",
      progress: 35,
      risk: "yellow",
      tier: "Eco",
    },
    {
      id: "p3",
      client: "Clínica dental Medellín",
      status: "Propuesta enviada",
      progress: 15,
      risk: "yellow",
      tier: "Pro",
    },
  ],

  socialChannels: [
    {
      platform: "instagram",
      label: "Instagram",
      reach: 12400,
      engagement: 4.8,
      metricLabel: "Alcance 7d",
      secondaryLabel: "Saves",
      secondaryValue: "186",
      trend: [8200, 9100, 10200, 11400, 11800, 12100, 12400],
      delta: { value: 12, label: "vs sem. ant.", direction: "up" },
    },
    {
      platform: "linkedin",
      label: "LinkedIn",
      reach: 6800,
      engagement: 2.1,
      metricLabel: "Impresiones 7d",
      secondaryLabel: "Clicks",
      secondaryValue: "94",
      trend: [4200, 4800, 5100, 5600, 6100, 6500, 6800],
      delta: { value: 8, label: "vs sem. ant.", direction: "up" },
    },
    {
      platform: "tiktok",
      label: "TikTok",
      reach: 3200,
      engagement: 6.2,
      metricLabel: "Views 7d",
      secondaryLabel: "Shares",
      secondaryValue: "42",
      trend: [1800, 2100, 2400, 2600, 2800, 3000, 3200],
      delta: { value: 15, label: "vs sem. ant.", direction: "up" },
    },
    {
      platform: "meta_ads",
      label: "Meta Ads",
      reach: 45200,
      engagement: 3.2,
      metricLabel: "ROAS",
      secondaryLabel: "Spend",
      secondaryValue: "$840",
      trend: [2.1, 2.4, 2.8, 2.9, 3.0, 3.1, 3.2],
      delta: { value: 0.4, label: "vs mes ant.", direction: "up" },
    },
  ],

  topPosts: [
    {
      id: "post1",
      platform: "instagram",
      hook: "5 errores que matan tu ROAS en e-commerce",
      reach: 4200,
      engagement: 6.1,
      saves: 89,
    },
    {
      id: "post2",
      platform: "linkedin",
      hook: "Cómo digitalizamos una operación completa con 12 agentes IA",
      reach: 3100,
      engagement: 3.4,
    },
    {
      id: "post3",
      platform: "tiktok",
      hook: "POV: tu agencia tiene un cerebro operativo llamado JARVIS",
      reach: 2800,
      engagement: 8.2,
      saves: 56,
    },
  ],

  alerts: [
    {
      id: "a1",
      level: "critical",
      message: "Cuenta por cobrar >30 días · E-commerce Cali · $2,400 USD",
      action: "Contactar cliente",
    },
    {
      id: "a2",
      level: "important",
      message: "Capacidad al 78% — evaluar freelancer en 2 semanas",
      action: "Revisar con HIVE",
    },
    {
      id: "a3",
      level: "important",
      message: "Propuesta clínica dental vence en 48h sin respuesta",
      action: "Follow-up HERMES",
    },
    {
      id: "a4",
      level: "info",
      message: "Meta Ads CPM subió 12% esta semana en sector salud",
    },
  ],

  priorities: [
    "Cerrar propuesta clínica dental Medellín ($8,500 setup)",
    "Deploy automatización WhatsApp GJS antes del lunes",
    "Publicar caso de estudio LinkedIn para generar inbound Q3",
  ],

  weeklyLeads: [
    { week: "S18", leads: 3, closes: 0 },
    { week: "S19", leads: 5, closes: 1 },
    { week: "S20", leads: 4, closes: 0 },
    { week: "S21", leads: 6, closes: 1 },
    { week: "S22", leads: 5, closes: 0 },
    { week: "S23", leads: 7, closes: 1 },
    { week: "S24", leads: 6, closes: 0 },
    { week: "S25", leads: 8, closes: 1 },
  ],

  finance: {
    revenueWeek: 3200,
    revenueMonth: 6200,
    revenueYtd: 14200,
    goal2026: 100000,
    runRateMonthly: 10500,
    runRateNeeded: 12500,
    pipelineWeighted: 45000,
    accountsReceivable: [
      { client: "E-commerce Cali", amount: 2400, days: 34 },
      { client: "Grupo Juana Sánchez", amount: 1500, days: 12 },
    ],
    expensesMonth: 420,
    expensesBudget: 600,
    marginByProject: [
      { client: "Grupo Juana Sánchez", revenue: 8500, cost: 2100, margin: 75 },
      { client: "E-commerce Cali", revenue: 3200, cost: 980, margin: 69 },
    ],
    revenueByTier: [
      { tier: "Eco", amount: 3200, color: "#10B981" },
      { tier: "Pro", amount: 8500, color: "#4F46E5" },
      { tier: "Premium", amount: 2500, color: "#1E6FFF" },
    ],
    monthlyRevenue: [
      { month: "Ene", projected: 0 },
      { month: "Feb", projected: 0 },
      { month: "Mar", projected: 0 },
      { month: "Abr", projected: 0 },
      { month: "May", actual: 8000, projected: 8000 },
      { month: "Jun", actual: 6200, projected: 10500 },
      { month: "Jul", projected: 13000 },
      { month: "Ago", projected: 14000 },
      { month: "Sep", projected: 14000 },
      { month: "Oct", projected: 16500 },
      { month: "Nov", projected: 16000 },
      { month: "Dic", projected: 13500 },
    ],
  },

  goals: [
    {
      id: "g1",
      title: "Facturación 2026",
      target: 100000,
      current: 14200,
      unit: "usd",
      deadline: "2026-12-31",
      status: "yellow",
    },
    {
      id: "g2",
      title: "Clientes activos Pro+",
      target: 8,
      current: 2,
      unit: "count",
      deadline: "2026-12-31",
      status: "yellow",
    },
    {
      id: "g3",
      title: "Pipeline cualificado",
      target: 50000,
      current: 45000,
      unit: "usd",
      deadline: "2026-09-30",
      status: "green",
    },
    {
      id: "g4",
      title: "Conexiones API activas",
      target: 7,
      current: 2,
      unit: "count",
      deadline: "2026-08-31",
      status: "red",
    },
    {
      id: "g5",
      title: "Engagement orgánico promedio",
      target: 5,
      current: 4.8,
      unit: "percent",
      deadline: "2026-12-31",
      status: "green",
    },
  ],

  okrs: [
    {
      id: "okr1",
      department: "Ventas · HERMES",
      objective: "Cerrar 3 clientes Pro en Q2",
      keyResults: [
        { label: "Propuestas enviadas", progress: 80 },
        { label: "Tasa cierre ≥25%", progress: 33 },
        { label: "Pipeline $50K", progress: 90 },
      ],
    },
    {
      id: "okr2",
      department: "Marketing · ARES",
      objective: "Generar 40 leads cualificados/mes",
      keyResults: [
        { label: "Leads score ≥6", progress: 45 },
        { label: "CAC ≤ $120", progress: 72 },
        { label: "ROAS ≥ 3x", progress: 100 },
      ],
    },
    {
      id: "okr3",
      department: "Plataforma · FORGE",
      objective: "Completar Capa 1 operativa",
      keyResults: [
        { label: "Panel + JARVIS live", progress: 85 },
        { label: "7 APIs conectadas", progress: 29 },
        { label: "Primer SOP automatizado", progress: 60 },
      ],
    },
    {
      id: "okr4",
      department: "Estrategia · ZEUS",
      objective: "Run rate $12.5K/mes sostenido",
      keyResults: [
        { label: "Revenue junio ≥ $10.5K", progress: 59 },
        { label: "Margen bruto ≥ 65%", progress: 73 },
        { label: "0 churn clientes", progress: 100 },
      ],
    },
  ],

  contentCalendar: [
    {
      id: "c1",
      date: "2026-06-21",
      platform: "linkedin",
      title: "Behind the scenes: JARVIS command center",
      status: "scheduled",
    },
    {
      id: "c2",
      date: "2026-06-22",
      platform: "instagram",
      title: "Carrusel: 5 señales de que necesitas IA",
      status: "draft",
    },
    {
      id: "c3",
      date: "2026-06-23",
      platform: "tiktok",
      title: "Day in the life · agencia IA Colombia",
      status: "scheduled",
    },
    {
      id: "c4",
      date: "2026-06-24",
      platform: "linkedin",
      title: "Caso éxito Grupo Juana Sánchez",
      status: "draft",
    },
    {
      id: "c5",
      date: "2026-06-25",
      platform: "instagram",
      title: "Reel: antes/después digitalización",
      status: "scheduled",
    },
  ],

  agents: AGENTS,
};
